### ISSUE TITLE
Raises a stack overflow in debug mode 

### ISSUE THREAD

**Issue by cscetbon** [DelSkayn/reblessive#4]
On MacOs Sequoia, I just run the example and I get
```
$ cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/test-reblessive`

thread 'main' has overflowed its stack
fatal runtime error: stack overflow
```

It doesn't happen if I run it in release mode
```
$ cargo run --release
   Compiling reblessive v0.4.1
   Compiling test-reblessive v0.1.0 (/Users/cscetbon/Downloads/test/test-reblessive)
    Finished `release` profile [optimized] target(s) in 1.18s
     Running `target/release/test-reblessive`
result: 10946
Timed out!
```

**Comment by DelSkayn** [comment]
Rust stack usage in debug mode is very unpredictable and can become massive. The overflow here is probably caused by the stack size of the function calls becoming so large in debug mode that it overflows immediately. Reblessive can't do anything to prevent that. 

The examples worked on my machine but probably fail on yours as your platform might have a different default stack size. The fact that release mod doesn't overflow indicates that reblessive works to prevent stack overflows in the cases where it can. Each recursive call takes at least 1MB of stack and unless your system has a default stack size of more then 20 MB it would have overflowed.

**Comment by cscetbon** [comment]
Okay closing it then, thanks
